import os
import glob
import re
import shutil
import json
from bs4 import BeautifulSoup

source_html_dir = r"C:\Users\onerock\Downloads\PROJECT\Interviews\Books_HTML"
target_base_dir = r"C:\Users\onerock\Downloads\PROJECT\AniketDeshmane.github.io\src\Books"
template_dir = r"C:\Users\onerock\Downloads\PROJECT\AniketDeshmane.github.io\src\HedgeFundEngineering"

os.makedirs(target_base_dir, exist_ok=True)

html_files = glob.glob(os.path.join(source_html_dir, "*.html"))

for html_path in html_files:
    filename = os.path.basename(html_path)
    book_name_raw = os.path.splitext(filename)[0]
    
    # Safe slug for the URL directory
    safe_slug = re.sub(r'[^a-zA-Z0-9]', '_', book_name_raw)
    safe_slug = re.sub(r'_+', '_', safe_slug).strip('_')[:50]
    
    book_dir = os.path.join(target_base_dir, safe_slug)
    os.makedirs(book_dir, exist_ok=True)
    
    # Copy images folder if it exists
    images_src = os.path.join(source_html_dir, book_name_raw + "_images")
    images_dst = os.path.join(book_dir, book_name_raw + "_images")
    if os.path.exists(images_src):
        if os.path.exists(images_dst):
            shutil.rmtree(images_dst)
        shutil.copytree(images_src, images_dst)
        
    # Copy shell files
    shutil.copy(os.path.join(template_dir, "index.html"), os.path.join(book_dir, "index.html"))
    shutil.copy(os.path.join(template_dir, "styles.css"), os.path.join(book_dir, "styles.css"))
    shutil.copy(os.path.join(template_dir, "app.js"), os.path.join(book_dir, "app.js"))
    
    # Parse HTML
    with open(html_path, 'r', encoding='utf-8') as f:
        html_content = f.read()
        
    soup = BeautifulSoup(html_content, 'html.parser')
    
    lessons = []
    
    headers = soup.find_all('h1')
    if len(headers) < 3:
        headers = soup.find_all('h2')
    if len(headers) < 3:
        headers = soup.find_all('h3')
        
    if len(headers) == 0:
        lessons.append({
            "id": "full-book",
            "title": "Full Content",
            "readTime": "120 min read",
            "subtitle": "",
            "content": soup.body.decode_contents() if soup.body else str(soup)
        })
    else:
        for idx, header in enumerate(headers):
            title = header.get_text(strip=True)[:100]
            if not title:
                title = f"Section {idx+1}"
            
            content_html = ""
            sibling = header.find_next_sibling()
            while sibling and sibling.name != header.name:
                content_html += str(sibling)
                sibling = sibling.find_next_sibling()
                
            lessons.append({
                "id": f"lesson-{idx}",
                "title": title,
                "readTime": "5 min read",
                "subtitle": "",
                "content": content_html
            })
            
    course_data = [
        {
            "id": safe_slug,
            "title": book_name_raw[:40] + "...",
            "bookTag": "Interview Book",
            "lessons": lessons
        }
    ]
    
    js_content = f"// Auto-generated by agent\nconst COURSE_DATA = {json.dumps(course_data)};\n"
    with open(os.path.join(book_dir, "content.js"), "w", encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Processed {book_name_raw} -> {safe_slug} ({len(lessons)} lessons)")
